#!/bin/bash

# Call example: ./vm

function clone_project {
    project=$1
    branch=$2
    giturl=https://github.com/projectestac/$project.git
    clone_project_git "$project" "$giturl" "$branch"
}

function clone_project_git {
    project=$1
    giturl=$2
    branch=$3
    homedir=$(pwd)
    if [ ! -d "$homedir/../$project" ]; then
        echo "Project $project not found, cloning..."
        git clone "$giturl" "$homedir/../$project"
        if [[ "$branch" != "master" ]]; then
            pushd "$homedir/../$project" || return
            git checkout -b "$branch" "origin/$branch"
            popd || return
        fi
        pushd "$homedir/../$project" || return
        git submodule update --recursive --init
        popd || return
    fi
}

git pull origin agora-ubuntu-php74

if ! vagrant plugin list | grep -q vagrant-hosts; then
    vagrant plugin install vagrant-hosts
fi

if ! vagrant plugin list | grep -q vagrant-disksize; then
    vagrant plugin install vagrant-disksize
fi

clone_project agora master

vagrant box update

echo "Starting the VM"
vagrant up --provider virtualbox
